# runtime: nodejs16
# handlers:
# - url: /
#   static_files: build/index.html
#   upload: build/index.html
# - url: /
#   static_dir: buildapiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webiso
  namespace: '884818606592'
  selfLink: /apis/serving.knative.dev/v1/namespaces/884818606592/services/webiso
  uid: 9529db04-3b49-488a-b9f6-c95cb14f0d7d
  resourceVersion: AAYghNke4zk
  generation: 1
  creationTimestamp: '2024-08-25T16:53:11.740349Z'
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: isos.smart.osh@gmail.com
    serving.knative.dev/lastModifier: isos.smart.osh@gmail.com
    run.googleapis.com/operation-id: ca0150b4-18ab-48f5-ba96-b9b6a2173ba7
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: osiris@sunlit-form-430600-n9.iam.gserviceaccount.com
      containers:
      - name: placeholder-1
        image: gcr.io/cloudrun/placeholder
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 1
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2024-08-25T16:53:30.715961Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2024-08-25T16:53:11.976092Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2024-08-25T16:53:30.681047Z'
  latestReadyRevisionName: webiso-00001-ncr
  latestCreatedRevisionName: webiso-00001-ncr
  traffic:
  - revisionName: webiso-00001-ncr
    percent: 100
    latestRevision: true
  url: https://webiso-2tanbbatta-uc.a.run.app
  address:
    url: https://webiso-2tanbbatta-uc.a.run.app